name: Deploy to App Store
on:
  push:
    branches: [ main, master ]

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload to App Store
        uses: apple-actions/upload-release-asset@v1
        env:
          APPLE_ID: ${{ secrets.APPLEID }}
          APPLE_PASSWORD: ${{ secrets.APPLEPASSWORD }}
        with:
          upload_url: https://apple.com
          asset_path: build/ios/archive/Runner.xcarchive
